- hosts: all
  become: true
  become_user: root
  tasks:

  - name: copying deploment files
    become: true 
    copy:
      src: /media/waer/New Volume/Created_by_me/SW_Reops/SW-DevOps/Docker-Compose/
      dest: /Read-it/deployment/

  - name: check permission of docker socke
    ansible.builtin.file:
      path: /var/run/docker.sock
      owner: "root"
      group: "root"
      mode: '0666'
